name: Generate package - SQLCover


on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build and Publish
    runs-on: windows-latest

    steps:
      # -------------------------------------------------
      # Checkout
      # -------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------------------------
      # Setup .NET
      # -------------------------------------------------
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '6.0.x'
                
      # -------------------------------------------------
      # Build
      # -------------------------------------------------
      - name: Build solution
        run:  |
          echo "Building Solution..."
          .\.build\_init.ps1
          Build `

      # -------------------------------------------------
      # Pack
      # -------------------------------------------------
      - name: Pack NuGet package
        shell: pwsh
        run: |  
          nuget pack `
            nuspec/SqlCover.nuspec `
            -BasePath nuget `
            -OutputDirectory packages `
            -NonInteractive


      # -------------------------------------------------
      # Verify package
      # -------------------------------------------------
      - name: Verify package contents
        shell: pwsh
        run: |
          Expand-Archive packages\*.nupkg extracted -Force
          Get-ChildItem -Recurse extracted

      # -------------------------------------------------
      # Publish
      # -------------------------------------------------
      - name: Publish to NuGet
        if: github.ref == 'refs/heads/publish-package'
        uses: ./.github/actions/push-package
        with:
          path: ./packages
          package: RedGate.ThirdParty.SqlCover